tasks:
  - name: Install dependencies
    init: |
      pyenv install 3.8
      pyenv local 3.8
      pip install -r requirements-dev.txt
      pip install --use-deprecated=legacy-resolver rasa-x --extra-index-url https://pypi.rasa.com/simple
      python3 -m spacy download en_core_web_trf
      gp sync-done prepare
  - name: Generate
    init: |
      gp sync-await prepare # wait for the above 'init' to finish
      python3 -m data_generation.utils.generate_chatbot
      gp sync-done generate
  - name: Train
    init: |
      gp sync-await generate # wait for the above 'init' to finish
      python3 -m rasa train --domain=domain --force
  - name: Action Server
    command: python3 -m rasa_sdk --actions actions
  - name: Duckling Server
    command: docker run -p 8000:8000 rasa/duckling
  - name: Rasa X
    command: python3 -m rasa x --domain=domain

ports:
  - port: 5002
