version: "3.9"
   
services:
  actions:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"
  core:
    build:
      context: ./
      =
      dockerfile: Dockerfile.core
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    depends_on:
      - actions
      - duckling