steps:
# Build the alpine and debian versions.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'docker/Dockerfile.trained', '--tag=gcr.io/$PROJECT_ID/trained', '--build-arg', 'DUCKLING_HOST_ARG=${_DUCKLING_HOST}', '.']
images: ['gcr.io/$PROJECT_ID/trained']
timeout: 3600s