FROM python:3.8.0

WORKDIR /app
COPY . /app

# Downgrade pip
RUN pip install --upgrade pip==20.2

# Install git
RUN apt-get update && apt-get install -y git

# Install production dependencies.
COPY ./requirements.txt .
RUN pip install -r requirements-dev.txt
