FROM gcr.io/chatbot-299615/base

ARG DUCKLING_HOST_ARG
ENV DUCKLING_HOST=${DUCKLING_HOST_ARG}

# Download spacy again because the next step doesn't work otherwise
RUN pip install spacy
# Download trained spacy pipeline
RUN python -m spacy download en_core_web_md

# Generate NLU
RUN python -m data_generation.utils.generate_chatbot

# Train
ARG DUCKLING_HOST
RUN python -m rasa train --domain=domain