FROM python:3.8.0

# Downgrade pip
RUN pip install --upgrade pip==20.2

# Install git
RUN apt-get update && apt-get install -y git

# Install production dependencies.
COPY ./requirements.txt .
COPY ./actions/requirements-actions.txt ./actions/
RUN pip install -r requirements.txt
