# FROM rasa/rasa:latest-full 
FROM python:3.8.0-slim

WORKDIR /app
COPY . /app
COPY ./data /app/data
COPY ./domain /app/domain

# Install git
RUN apt-get update && apt-get install -y git

# Install production dependencies.
COPY ./requirements.txt .
RUN pip install -r requirements.txt

VOLUME /app
VOLUME /app/data
VOLUME /app/models
VOLUME /app/channels
VOLUME /app/services

CMD ["python","-m","rasa_sdk","--actions","actions" ]