ARG CHATBOT_ID_ARG
FROM gcr.io/chatbot-299615/trained:${CHATBOT_ID_ARG}

COPY ./supervisor /app/supervisor

# Install supervisor
RUN apt-get update && apt-get install -y supervisor

# Install netstat
RUN apt-get install net-tools

CMD ["supervisord", "-c", "supervisor/rasa-run-nlu.conf"]
